---
abstract: 'the basic plugins to maintain and release ACPS dists'
author:
  - 'Graham Ollis <gollis@sesda2.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-ACPS
requires:
  Carp: 0
  Cwd: 0
  DateTime: 0
  Dist::Zilla: 0
  Dist::Zilla::App: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::AfterMint: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::BuildPL: 0
  Dist::Zilla::Role::Git::DirtyFiles: 0
  Dist::Zilla::Role::Git::Repo: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::Plugin: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Role::Releaser: 0
  Dist::Zilla::Role::VersionProvider: 0
  File::Copy: 0
  File::HomeDir: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::chdir: 0
  Git::Wrapper: 0.021
  IPC::Open3: 0
  IPC::System::Simple: 0
  List::MoreUtils: 0
  Moose: 0
  MooseX::AttributeShortcuts: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Path::Class::Dir: 0
  String::Formatter: 0
  Template: 0
  Try::Tiny: 0
  autodie: 0
  namespace::autoclean: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.07
